In [13]:
import numpy as np

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix Operation")
print(f"Matrix A : \n {A}")
print(f"Matrix B : \n {B}")

print("Matrix Addition : \n",A + B)
print("Matrix Subtraction : \n",B - A)
print("Matrix Multiplication : \n",np.dot(A,B))
print("Transpose : \n",A.T)
print("Transpose : \n",B.T)

Matrix Operation
Matrix A : 
 [[1 2]
 [3 4]]
Matrix B : 
 [[5 6]
 [7 8]]
Matrix Addition : 
 [[ 6  8]
 [10 12]]
Matrix Subtraction : 
 [[4 4]
 [4 4]]
Matrix Multiplication : 
 [[19 22]
 [43 50]]
Transpose : 
 [[1 3]
 [2 4]]
Transpose : 
 [[5 7]
 [6 8]]
