In [3]:
import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
u,s,vt=np.linalg.svd(x)
n_components=2
x_reconstructed=np.dot(u[:,:n_components],np.dot(np.diag(s[:n_components]),vt[:n_components,:]))
print("original matrix : ")
print(x)
print("\n Reconstructed Matrix(with reduced dimensions) : ")
print(x_reconstructed)

original matrix : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Reconstructed Matrix(with reduced dimensions) : 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
